services:
  development:
    image: bxt_development:latest
    build:
      context: .
      target: development
      args:
        - USERNAME=${USER:-developer}
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
        - LLVM_VERSION=${LLVM_VERSION:-20}
    network_mode: host
    volumes:
      - .:/home/${USER:-developer}/workspace # Mount current directory to workspace
      - /home/${USER}/.gitconfig:/home/${USER:-developer}/.gitconfig:ro # Git config
      - /home/${USER}/.ssh:/home/${USER:-developer}/.ssh:ro
    environment:
      - DISPLAY=${DISPLAY:-}
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
